#!/bin/sh

rm -f ./env.js
touch ./env.js

# remove double or single quotes around values, if any
SERVER_URL=${SERVER_URL#\"}
SERVER_URL=${SERVER_URL%\"}
SERVER_URL=${SERVER_URL#\'}
SERVER_URL=${SERVER_URL%\'}

WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL#\"}
WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL%\"}
WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL#\'}
WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL%\'}

CLIENT_SHOW_EMAIL_LOGIN_OPTION=${CLIENT_SHOW_EMAIL_LOGIN_OPTION#\"}
CLIENT_SHOW_EMAIL_LOGIN_OPTION=${CLIENT_SHOW_EMAIL_LOGIN_OPTION%\"}
CLIENT_SHOW_EMAIL_LOGIN_OPTION=${CLIENT_SHOW_EMAIL_LOGIN_OPTION#\'}
CLIENT_SHOW_EMAIL_LOGIN_OPTION=${CLIENT_SHOW_EMAIL_LOGIN_OPTION%\'}

CLIENT_BIOINTERACTIVE_OAUTH_CLIENT_ID=${CLIENT_BIOINTERACTIVE_OAUTH_CLIENT_ID#\"}
CLIENT_BIOINTERACTIVE_OAUTH_CLIENT_ID=${CLIENT_BIOINTERACTIVE_OAUTH_CLIENT_ID%\"}
CLIENT_BIOINTERACTIVE_OAUTH_CLIENT_ID=${CLIENT_BIOINTERACTIVE_OAUTH_CLIENT_ID#\'}
CLIENT_BIOINTERACTIVE_OAUTH_CLIENT_ID=${CLIENT_BIOINTERACTIVE_OAUTH_CLIENT_ID%\'}

CLIENT_BIOINTERACTIVE_OAUTH_REDIRECT_URI=${CLIENT_BIOINTERACTIVE_OAUTH_REDIRECT_URI#\"}
CLIENT_BIOINTERACTIVE_OAUTH_REDIRECT_URI=${CLIENT_BIOINTERACTIVE_OAUTH_REDIRECT_URI%\"}
CLIENT_BIOINTERACTIVE_OAUTH_REDIRECT_URI=${CLIENT_BIOINTERACTIVE_OAUTH_REDIRECT_URI#\'}
CLIENT_BIOINTERACTIVE_OAUTH_REDIRECT_URI=${CLIENT_BIOINTERACTIVE_OAUTH_REDIRECT_URI%\'}


cat <<EOF > ./env.js
window.env = {
    serverUrl: '${SERVER_URL}',
    websocketServerUrl: '${WEBSOCKET_SERVER_URL}',    
    show_email_login: '${CLIENT_SHOW_EMAIL_LOGIN_OPTION}',    
    oauth_client_id: '${CLIENT_BIOINTERACTIVE_OAUTH_CLIENT_ID}',    
    oauth_redirect_uri: '${CLIENT_BIOINTERACTIVE_OAUTH_REDIRECT_URI}',    
}
EOF

exec "$@"
