stages:
  - install
  - lint
  - deploy-storybook

lint js:
  image: node:12-alpine
  stage: lint
  script:
    - yarn install && cd packages/client && yarn install && cd ../.. && cd packages/server && yarn install && cd ../..
    - yarn eslint .

deploy storybook static:
  image: debian:stable-slim
  stage: deploy-storybook
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh ${SSH_USER}@${SSH_URL} -p ${SSH_PORT} "cd ${APP_ROOT_PATH} && bash ./scripts/storybook-deploy.sh"
  only:
    - master
