variables:
  IMAGE_ORG: cokoapps
  IMAGE_NAME_SERVER_DEVELOPMENT: hhmi-server-ci-development
  IMAGE_NAME_CLIENT_DEVELOPMENT: hhmi-client-ci-development
  IMAGE_NAME_SERVER_PREPRODUCTION: hhmi-server-ci-production
  IMAGE_NAME_CLIENT_PREPRODUCTION: hhmi-client-ci-production
  IMAGE_NAME_SERVER_PRODUCTION: hhmi-server
  IMAGE_NAME_CLIENT_PRODUCTION: hhmi-client
  IMAGE_NAME_STORYBOOK: hhmi-storybook
  CYPRESS_RECORD_KEY: a25f8612-45b7-4f19-941d-6fd738b181c1
  WORKDIR_SERVER: /home/node/hhmi
  WORKDIR_CLIENT: /home/node/app

stages:
  - Build development
  - Lint & Unit test
  - Build production
  - End to end test
  - Publish production
  - Deploy production

# BUILD DEVELOPMENT

.client build development:
  stage: Build development
  image: docker:26
  services:
    - docker:26-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker build --tag $IMAGE_ORG/$IMAGE_NAME_CLIENT_DEVELOPMENT:$CI_COMMIT_SHA ./packages/client -f packages/client/Dockerfile-development
    - docker push $IMAGE_ORG/$IMAGE_NAME_CLIENT_DEVELOPMENT:$CI_COMMIT_SHA

.server build development:
  stage: Build development
  image: docker:26
  services:
    - docker:26-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker build --tag $IMAGE_ORG/$IMAGE_NAME_SERVER_DEVELOPMENT:$CI_COMMIT_SHA ./packages/server -f packages/server/Dockerfile-development
    - docker push $IMAGE_ORG/$IMAGE_NAME_SERVER_DEVELOPMENT:$CI_COMMIT_SHA

# LINT & UNIT TEST

.client lint:
  stage: Lint & Unit test
  needs:
    - client build development
  image: $IMAGE_ORG/$IMAGE_NAME_CLIENT_DEVELOPMENT:$CI_COMMIT_SHA
  script:
    - cd $WORKDIR_CLIENT
    - yarn eslint .
    - yarn prettier --check .
    - yarn stylelint "**/*.js"

.client unit test:
  stage: Lint & Unit test
  needs:
    - client build development
  image: $IMAGE_ORG/$IMAGE_NAME_CLIENT_DEVELOPMENT:$CI_COMMIT_SHA
  script:
    - cd $WORKDIR_CLIENT
    - yarn jest

.server lint:
  stage: Lint & Unit test
  needs:
    - server build development
  image: $IMAGE_ORG/$IMAGE_NAME_SERVER_DEVELOPMENT:$CI_COMMIT_SHA
  script:
    - cd $WORKDIR_SERVER
    - yarn eslint .
    - yarn prettier --check .

.server unit test:
  stage: Lint & Unit test
  needs:
    - server build development
  image: docker:23
  services:
    - docker:23-dind
  script:
    - cp .env.ci .env
    - docker-compose up -d server db
    - docker pull $IMAGE_ORG/$IMAGE_NAME_SERVER_DEVELOPMENT:$CI_COMMIT_SHA
    - |
      docker run \
      --network hhmi_default \
      -e POSTGRES_HOST=db -e POSTGRES_PORT=5432 -e POSTGRES_DB=hhmi_dev -e POSTGRES_USER=hhmi_dev_user -e POSTGRES_PASSWORD=hhmi_dev_user_password \
      -e BIOINTERACTIVE_OAUTH_API_USER_URI=bio.int/api -e BIOINTERACTIVE_OAUTH_TOKEN_URI=bio.int/token -e BIOINTERACTIVE_OAUTH_CLIENT_ID=123 -e BIOINTERACTIVE_OAUTH_CLIENT_SECRET=321 -e BIOINTERACTIVE_OAUTH_REDIRECT_URI=hhmi.co/biointeractive-oauth \
      -e PUBSWEET_SECRET=superSecretThing \
      $IMAGE_ORG/$IMAGE_NAME_SERVER_DEVELOPMENT:$CI_COMMIT_SHA \
      yarn jest --verbose --forceExit

# BUILD PRODUCTION

.build server:
  stage: Build production
  image: docker:26
  services:
    - docker:26-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - cd ./packages/server
    - docker pull $IMAGE_ORG/$IMAGE_NAME_SERVER_PREPRODUCTION:latest || true
    - docker build --cache-from $IMAGE_ORG/$IMAGE_NAME_SERVER_PREPRODUCTION:latest --tag $IMAGE_ORG/$IMAGE_NAME_SERVER_PREPRODUCTION:$CI_COMMIT_SHA --tag $IMAGE_ORG/$IMAGE_NAME_SERVER_PREPRODUCTION:latest . -f Dockerfile-server-deploy
    - docker push $IMAGE_ORG/$IMAGE_NAME_SERVER_PREPRODUCTION:$CI_COMMIT_SHA
    - docker push $IMAGE_ORG/$IMAGE_NAME_SERVER_PREPRODUCTION:latest

.build client:
  stage: Build production
  image: docker:26
  services:
    - docker:26-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - cd ./packages/client
    - docker pull $IMAGE_ORG/$IMAGE_NAME_CLIENT_PREPRODUCTION:latest || true
    - docker build --cache-from $IMAGE_ORG/$IMAGE_NAME_CLIENT_PREPRODUCTION:latest --tag $IMAGE_ORG/$IMAGE_NAME_CLIENT_PREPRODUCTION:$CI_COMMIT_SHA --tag $IMAGE_ORG/$IMAGE_NAME_CLIENT_PREPRODUCTION:latest . -f Dockerfile-client-deploy
    - docker push $IMAGE_ORG/$IMAGE_NAME_CLIENT_PREPRODUCTION:$CI_COMMIT_SHA
    - docker push $IMAGE_ORG/$IMAGE_NAME_CLIENT_PREPRODUCTION:latest

# END TO END TEST

.end to end tests:
  stage: End to end test
  image: cokoapps/hhmi-dnn
  needs:
    - build client
    - build server
  script:
    - cp .env.ci .env
    - source .env
    - CLIENT_SHOW_EMAIL_LOGIN_OPTION=true
    - docker compose --compatibility -f docker-compose.cypress-ci.yml up -d
    - docker compose ps
    - yarn install --frozen-lockfile
    - wait-on --timeout 30000 http://localhost:3000/healthcheck && yarn cypress run --record --env CLIENT_SHOW_EMAIL_LOGIN_OPTION=true

# PUBLISH PRODUCTION

publish client:
  stage: Publish production
  image: docker:26
  services:
    - docker:26-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker pull $IMAGE_ORG/$IMAGE_NAME_CLIENT_PREPRODUCTION:$CI_COMMIT_SHA
    - docker tag $IMAGE_ORG/$IMAGE_NAME_CLIENT_PREPRODUCTION:$CI_COMMIT_SHA $IMAGE_ORG/$IMAGE_NAME_CLIENT_PRODUCTION:$CI_COMMIT_SHA
    - docker tag $IMAGE_ORG/$IMAGE_NAME_CLIENT_PREPRODUCTION:$CI_COMMIT_SHA $IMAGE_ORG/$IMAGE_NAME_CLIENT_PRODUCTION:latest
    - docker push $IMAGE_ORG/$IMAGE_NAME_CLIENT_PRODUCTION:$CI_COMMIT_SHA
    - docker push $IMAGE_ORG/$IMAGE_NAME_CLIENT_PRODUCTION:latest
  only:
    - staging

publish server:
  stage: Publish production
  image: docker:26
  services:
    - docker:26-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker pull $IMAGE_ORG/$IMAGE_NAME_SERVER_PREPRODUCTION:$CI_COMMIT_SHA
    - docker tag $IMAGE_ORG/$IMAGE_NAME_SERVER_PREPRODUCTION:$CI_COMMIT_SHA $IMAGE_ORG/$IMAGE_NAME_SERVER_PRODUCTION:$CI_COMMIT_SHA
    - docker tag $IMAGE_ORG/$IMAGE_NAME_SERVER_PREPRODUCTION:$CI_COMMIT_SHA $IMAGE_ORG/$IMAGE_NAME_SERVER_PRODUCTION:latest
    - docker push $IMAGE_ORG/$IMAGE_NAME_SERVER_PRODUCTION:$CI_COMMIT_SHA
    - docker push $IMAGE_ORG/$IMAGE_NAME_SERVER_PRODUCTION:latest
  only:
    - staging

build & publish storybook:
  stage: Publish production
  image: docker:26
  services:
    - docker:26-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - cd ./packages/client
    - docker pull $IMAGE_ORG/$IMAGE_NAME_STORYBOOK:latest || true
    - docker build --cache-from $IMAGE_ORG/$IMAGE_NAME_STORYBOOK:latest --tag $IMAGE_ORG/$IMAGE_NAME_STORYBOOK:$CI_COMMIT_SHA --tag $IMAGE_ORG/$IMAGE_NAME_STORYBOOK:latest . -f Dockerfile-storybook-production
    - docker push $IMAGE_ORG/$IMAGE_NAME_STORYBOOK:$CI_COMMIT_SHA
    - docker push $IMAGE_ORG/$IMAGE_NAME_STORYBOOK:latest
  only:
    - staging

# DEPLOY PRODUCTION

deploy production:
  stage: Deploy production
  image: $CI_REGISTRY/cokoinfra/ansible-deployer
  services:
    - docker:26-dind
  variables:
    ANSCOMPOSE_POSTGRES_ALLOW_SELF_SIGNED_CERTIFICATES: true
    ANSCOMPOSE_CLIENT_SHOW_EMAIL_LOGIN_OPTION: true
    COMPOSE_SERVICES: client,server
    COMPOSE_SERVICES_CLIENT_URL: hhmi.coko.app
    COMPOSE_SERVICES_CLIENT_IMAGE: $IMAGE_ORG/$IMAGE_NAME_SERVER_PRODUCTION:latest
    COMPOSE_SERVICES_SERVER_URL: hhmi-server.coko.app
    COMPOSE_SERVICES_SERVER_IMAGE: $IMAGE_ORG/$IMAGE_NAME_CLIENT_PRODUCTION:latest
    DEPLOY_COMPOSE_FILE: docker-compose.deploy.yml
  script:
    - kubectl config get-contexts
    - kubectl config use-context coko-org/products/hhmi/agent:agent-1
    - cp $DEPLOY_COMPOSE_FILE /ansible
    - cd /ansible
    - kubectl get -n default secrets digitalocean-spaces-credentials
    - ANSIBLE_FORCE_COLOR=true ansible-playbook bootstrap.yml -e "compose_file=$DEPLOY_COMPOSE_FILE"
  only:
    - staging



# deploy production:
#   image: debian:bullseye-slim
#   stage: Deploy production
#   needs:
#     - publish server
#     - publish client
#   before_script:
#     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
#     - chmod 700 ~/.ssh
#     - ssh-keyscan -p $SSH_PORT $SSH_URL >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#   script:
#     - |
#       ssh ${SSH_USER}@${SSH_URL} -p ${SSH_PORT} \
#       "docker pull $IMAGE_ORG/$IMAGE_NAME_SERVER_PRODUCTION:latest && \
#       docker pull $IMAGE_ORG/$IMAGE_NAME_CLIENT_PRODUCTION:latest && \
#       sudo systemctl restart hhmi.service"
#   only:
#     - staging

# deploy storybook:
#   image: debian:bullseye-slim
#   stage: Deploy production
#   needs:
#     - build & publish storybook
#   before_script:
#     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
#     - eval $(ssh-agent -s)
#     - echo "$STORYBOOK_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
#     - chmod 700 ~/.ssh
#     - ssh-keyscan -p $STORYBOOK_SSH_PORT $STORYBOOK_SSH_URL >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#   script:
#     - |
#       ssh ${STORYBOOK_SSH_USER}@${STORYBOOK_SSH_URL} -p ${STORYBOOK_SSH_PORT} \
#       "docker pull $IMAGE_ORG/$IMAGE_NAME_STORYBOOK:latest && \
#       docker stop $IMAGE_NAME_STORYBOOK && \
#       docker rm $IMAGE_NAME_STORYBOOK && \
#       docker run -d -p 5410:80 --name $IMAGE_NAME_STORYBOOK $IMAGE_ORG/$IMAGE_NAME_STORYBOOK"
#   only:
#     - master
