variables:
  IMAGE_ORG: cokoapps
  IMAGE_NAME: hhmi-server-ci-development
  WORKDIR: /home/node/hhmi

stages:
  - Build
  - Lint & Test
  - Deploy
  # - install
  # - deploy-storybook

server build development:
  stage: Build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker build --tag $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA ./packages/server -f packages/server/Dockerfile-development
    - docker push $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA

server lint js:
  stage: Lint & Test
  needs:
    - server build development
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  script:
    - cd $WORKDIR
    - yarn eslint .

server unit test:
  stage: Lint & Test
  needs:
    - server build development
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - ls -la
    - docker-compose --version
  script:
    - docker-compose up -d db
    - docker pull $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
    - |
      docker run \
      --network hhmi_default \
      -e NODE_ENV=test \
      -e POSTGRES_HOST=db -e POSTGRES_PORT=5432 -e POSTGRES_DB=hhmi_dev -e POSTGRES_USER=hhmi_dev_user -e POSTGRES_PASSWORD=hhmi_dev_user_password \
      $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA \
      yarn jest --verbose

    # NODE_ENV=test
    #   POSTGRES_HOST=localhost POSTGRES_PORT=5432 POSTGRES_DB=hhmi_dev POSTGRES_USER=hhmi_dev_user POSTGRES_PASSWORD=hhmi_dev_user_password
    #   PUBSWEET_SECRET=superSecretThing
    #   S3_PROTOCOL=http S3_HOST=localhost S3_PORT=9000 S3_ACCESS_KEY_ID=nonRootUser S3_SECRET_ACCESS_KEY=nonRootPassword S3_BUCKET=uploads

    # SERVER_PORT=${SERVER_PORT:-3000}
    # CLIENT_PROTOCOL=${CLIENT_PROTOCOL:-http}
    # CLIENT_HOST=${CLIENT_HOST:-0.0.0.0}
    # CLIENT_PORT=${CLIENT_PORT:-4000}
    # MAILER_SENDER=${MAILER_SENDER:-dev@example.com}
    # MAILER_HOSTNAME=${MAILER_HOSTNAME}
    # MAILER_PORT=${MAILER_PORT}
    # MAILER_USER=${MAILER_USER}
    # MAILER_PASSWORD=${MAILER_PASSWORD}
    # PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH:-password-reset}

# deploy storybook static:
#   image: debian:stable-slim
#   stage: deploy-storybook
#   before_script:
#     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
#     - chmod 700 ~/.ssh
#     - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#   script:
#     - ssh ${SSH_USER}@${SSH_URL} -p ${SSH_PORT} "cd ${APP_ROOT_PATH} && bash ./scripts/storybook-deploy.sh"
#   only:
#     - master

# build storybook image:
#   stage: Build
#   image: docker:19.03.12
#   services:
#     - docker:19.03.12-dind
#   before_script:
#     - docker info
#     - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
#   script:
#     - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
#     - cd ./packages/client
#     - docker pull $IMAGE_ORG/hhmi-storybook:latest || true
#     - docker build --cache-from $IMAGE_ORG/hhmi-storybook:latest --tag $IMAGE_ORG/hhmi-storybook:$CI_COMMIT_SHA --tag $IMAGE_ORG/hhmi-storybook:latest . -f Dockerfile-storybook-deploy
#     - docker push $IMAGE_ORG/hhmi-storybook:$CI_COMMIT_SHA
#     - docker push $IMAGE_ORG/hhmi-storybook:latest
#   only:
#     - master

# deploy storybook:
#   image: debian:stable-slim
#   stage: Deploy
#   before_script:
#     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
#     - eval $(ssh-agent -s)
#     - echo "$STORYBOOK_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
#     - chmod 700 ~/.ssh
#     - echo "$STORYBOOK_SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#   script:
#     - ssh ${STORYBOOK_SSH_USER}@${STORYBOOK_SSH_URL} -p ${STORYBOOK_SSH_PORT} "docker pull cokoapps/hhmi-storybook:latest && docker stop hhmi-storybook && docker rm hhmi-storybook && docker run -d -p 5410:80 --name hhmi-storybook cokoapps/hhmi-storybook"
#   only:
#     - master
