# Consolidate the common configuration for reuse across multiple steps.
definitions:
  # Configure some default step values.
  step-defaults: &step-defaults
    timeout_in_minutes: 15
  plugins:
    ecr: &ecr
      ecr#v2.7.0:
        login: true
        no-include-email: true

  # Specify common agent queue parameters.
  queues:
    # Docker-based tasks should run in the Docker queue.
    docker-agents: &docker-agents
      agents:
        queue: "docker-builders"
  git-remote-repo: &git-remote-repo
    remote: shvqcj74czxki@git.us-2.platform.sh:shvqcj74czxki.git
  ssh-defaults: &ssh-defaults
    ssh:
      keyscan: git.us-2.platform.sh
  git: &git
    git:
      name: F1 Builder
      email: support+f1builder@forumone.com
env:
  # If you do not declare buildkit:1 then arguments using for --target
  # do not work correctly and they will build every steps.
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

  # Identify the address for the shared Buildkite ECR repository.
  IMAGE_REPOSITORY: "165761832703.dkr.ecr.us-east-1.amazonaws.com/buildkite"

  # Set this as an environment variable for automatic usage by default for all
  # docker-compose buildkite plugin executions.
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_IMAGE_REPOSITORY: "$IMAGE_REPOSITORY"

  # Define a common namespace for images to be published within the shared ECR repo.
  ECR_NAMESPACE: "${IMAGE_REPOSITORY}:${BUILDKITE_PIPELINE_SLUG}"

  # Define service directory were the Dockerfile is used
  DOCKERFILE_CLIENT: "./packages/client"
  DOCKERFILE_SERVER: "./packages/server"

  ARTIFACT_LOCATION_CLIENT: ${DOCKERFILE_CLIENT}/artifacts
  ARTIFACT_LOCATION_SERVER: ${DOCKERFILE_SERVER}/artifacts
steps:
  - label: ":hammer: :docker: Building Docker Image for Client"
    key: "build-image-client"
    <<: *step-defaults
    <<: *docker-agents
    command:
      - "docker build --target client-build -f ${DOCKERFILE_CLIENT}/Dockerfile-forumone -t ${ECR_NAMESPACE}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}-client ${DOCKERFILE_CLIENT} --build-arg SERVER_URL=${SERVER_URL}"
      - "docker push ${ECR_NAMESPACE}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}-client"
    plugins:
      - *ecr

  - label: ":hammer: :docker: Building Docker Image for Server"
    key: "build-image-server"
    <<: *step-defaults
    <<: *docker-agents
    command:
      - "docker build --target server-build -f ${DOCKERFILE_SERVER}/Dockerfile-forumone -t ${ECR_NAMESPACE}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}-server ${DOCKERFILE_SERVER}"
      - "docker push ${ECR_NAMESPACE}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}-server"
    plugins:
      - *ecr

  # Wait for images to finish building.
  - wait: ~

  # Deploy the built application.
  - label: ":pipeline: Deploy Client"
    key: "deploy-client"
    timeout_in_minutes: 15
    concurrency: 1
    concurrency_group: '$BUILDKITE_PIPELINE_SLUG/$BUILDKITE_BRANCH/deploy'
    branches:
      - integration
      - main
      - live
    plugins:
      # Log into ECR for this build step to access prebuilt images.
      - *ecr

      # Download the prebuilt image and extract project files to the
      # local filesystem for further operations.
      - forumone/extract#v0.2.0:
          verbose: true
          image: ${ECR_NAMESPACE}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}-client
          from: /home/node/app
          to: ${ARTIFACT_LOCATION_CLIENT}/client

      # Execute a Capistrano deployment using the defined branch to
      # environment mapping.
      #- forumone/capistrano#v0.5.1:
      - forumone/artifact-push#v0.3.1:
          verbose: true
          source-directory: ${ARTIFACT_LOCATION_CLIENT}
          <<: *git-remote-repo
          branches:
            - match: live
              target: prod
            - match: main
              target: main
            - match: integration
              target: integration
          <<: *ssh-defaults
          <<: *git
          files:
            force-add:
              - client
            ignore:
              - .platform
              - minio
              - server
              - drupal
              - client/.environment
              - client/platformsh-scripts

  - label: ":capistrano: Deploy Server"
    key: "deploy-server"
    depends_on: deploy-client
    timeout_in_minutes: 25
    concurrency: 1
    concurrency_group: '$BUILDKITE_PIPELINE_SLUG/$BUILDKITE_BRANCH/deploy-server'
    branches:
      - integration
      - main
      - live
    plugins:
      # Log into ECR for this build step to access prebuilt images.
      - *ecr

      # Download the prebuilt image and extract project files to the
      # local filesystem for further operations.
      - forumone/extract#v0.2.0:
          verbose: true
          image: ${ECR_NAMESPACE}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}-server
          from: /home/node/hhmi
          to: ${ARTIFACT_LOCATION_SERVER}/server

      # Execute a Capistrano deployment using the defined branch to
      # environment mapping.
      #- forumone/capistrano#v0.5.1:
      - forumone/artifact-push#v0.3.1:
          verbose: false
          source-directory: ${ARTIFACT_LOCATION_SERVER}
          <<: *git-remote-repo
          branches:
            - match: live
              target: prod
            - match: main
              target: main
            - match: integration
              target: integration
          <<: *ssh-defaults
          <<: *git
          files:
            force-add:
              - server
            ignore:
              - .platform/
              - minio
              - client
              - drupal
              - server/.environment
              - server/platformsh-scripts
