steps:
  - label: Build App
    command: buildkite-agent pipeline upload .buildkite/pipeline-base.yml
    branches:
      - live
    env:
      SERVER_URL: https://30779a260b80196a185294a3cb9a5745

  - label: Build App
    command: buildkite-agent pipeline upload .buildkite/pipeline-base.yml
    branches:
      - main
    env:
      SERVER_URL: https://30779a260b80196a185294a3cb9a5745

  - label: Build App
    command: buildkite-agent pipeline upload .buildkite/pipeline-base.yml
    branches:
      - '!live'
      - '!main'
    env:
      SERVER_URL: https://30779a260b80196a185294a3cb9a5745
