steps:
  - label: Build App
    command: buildkite-agent pipeline upload .buildkite/pipeline-base.yml
    branches:
      - live
    env:
      SERVER_URL: https://www.assessmentbuilder-node.hhmi.byf1.dev

  - label: Build App
    command: buildkite-agent pipeline upload .buildkite/pipeline-base.yml
    branches:
      - main
    env:
      SERVER_URL: https://stage.assessmentbuilder-node.hhmi.byf1.dev

  - label: Build App
    command: buildkite-agent pipeline upload .buildkite/pipeline-base.yml
    branches:
      - "!live"
      - "!main"
    env:
      SERVER_URL: https://dev.assessmentbuilder-node.hhmi.byf1.dev
