// import { emDash, ellipsis } from 'prosemirror-inputrules'
import { columnResizing, tableEditing } from 'prosemirror-tables'
import {
  InlineAnnotationsService,
  AnnotationToolGroupService,
  ImageService,
  ImageToolGroupService,
  LinkService,
  ListsService,
  ListToolGroupService,
  TablesService,
  TableToolGroupService,
  BaseService,
  BaseToolGroupService,
  DisplayTextToolGroupService,
  MathService,
  FullScreenService,
  FullScreenToolGroupService,
  SpecialCharactersService,
  SpecialCharactersToolGroupService,
  EditorInfoToolGroupServices,
  BottomInfoService,
  MultipleChoiceQuestionService,
  MultipleDropDownToolGroupService,
  FillTheGapQuestionService,
  FillTheGapToolGroupService,
  MatchingService,
  MatchingToolGroupService,
  MultipleChoiceDropDownToolGroupService,
  MultipleDropDownService,
  EssayService,
  EssayToolGroupService,
} from 'wax-prosemirror-services'

import { DefaultSchema } from 'wax-prosemirror-utilities'
// import { WaxSelectionPlugin } from 'wax-prosemirror-plugins'
// import invisibles, { hardBreak } from '@guardian/prosemirror-invisibles'

export default {
  MenuService: [
    {
      //   templateArea: 'mainMenuToolBar',
      //   toolGroups: [
      //     { name: 'Base', exclude: ['Save'] },
      //     {
      //       name: 'Annotations',
      //       more: [
      //         'Superscript',
      //         'Subscript',
      //         'SmallCaps',
      //         'Underline',
      //         'StrikeThrough',
      //       ],
      //     },
      //     'Lists',
      //     'Images',
      //     'Tables',
      //     'MultipleDropDown',
      //     'FillTheGap',
      //     'FullScreen',
      //   ],
      // },
      templateArea: 'mainMenuToolBar',
      toolGroups: [
        'Base',
        {
          name: 'Annotations',
          // exclude: ['LinkTool'],
          more: [
            'Superscript',
            'Subscript',
            'SmallCaps',
            'Underline',
            'StrikeThrough',
          ],
        },
        'Lists',
        'Images',
        'Tables',
        'MultipleChoiceDropDown',
        'Essay',
        'FillTheGap',
        'MultipleDropDown',
        'Matching',
        'FullScreen',
      ],
    },
  ],

  SchemaService: DefaultSchema,
  // RulesService: [emDash, ellipsis],

  // PmPlugins: [columnResizing(), tableEditing(), WaxSelectionPlugin],
  PmPlugins: [columnResizing(), tableEditing()],

  services: [
    new FillTheGapQuestionService(),
    new FillTheGapToolGroupService(),
    new MatchingService(),
    new MatchingToolGroupService(),
    new MultipleChoiceDropDownToolGroupService(),
    new MultipleChoiceQuestionService(),
    new MultipleDropDownService(),
    new MultipleDropDownToolGroupService(),
    new EssayService(),
    new EssayToolGroupService(),

    // new ListsService(),
    // new LinkService(),
    // new InlineAnnotationsService(),
    // new ImageService(),
    // new TablesService(),
    // new BaseService(),
    // new BaseToolGroupService(),
    // new TableToolGroupService(),
    // new ImageToolGroupService(),
    // new AnnotationToolGroupService(),
    // new ListToolGroupService(),
    // new DisplayTextToolGroupService(),
    // new MathService(),
    // new FullScreenService(),
    // new FullScreenToolGroupService(),
    // new SpecialCharactersService(),
    // new SpecialCharactersToolGroupService(),
    // new EditorInfoToolGroupServices(),
    // new BottomInfoService(),

    new ListsService(),
    new LinkService(),
    new InlineAnnotationsService(),
    new ImageService(),
    new TablesService(),
    new BaseService(),
    new BaseToolGroupService(),
    new TableToolGroupService(),
    new ImageToolGroupService(),
    new AnnotationToolGroupService(),
    new ListToolGroupService(),
    new DisplayTextToolGroupService(),
    new MathService(),
    new FullScreenService(),
    new FullScreenToolGroupService(),
    new SpecialCharactersService(),
    new SpecialCharactersToolGroupService(),
    new EditorInfoToolGroupServices(),
    new BottomInfoService(),
  ],
}
