drupal:
  type: 'php:8.1'
  size: M

  variables:
    php:
      memory_limit: 512M
      max_input_vars: 3000

  # dependencies:
  #   php:
  #     composer/composer: '^2'

  build:
    flavor: none

  source:
    root: drupal

  hooks:
    # The build hook runs after Composer to finish preparing up your code.
    # No services are available but the disk is writeable.
    build: |
      set -e
    # mkdir -p public/drupal
    # find . -mindepth 1 -maxdepth 1 -exec mv -t.. -- {} +


    # The deploy hook runs after your application has been deployed and started.
    # Code cannot be modified at this point but the database is available.
    # The site is not accepting requests while this script runs so keep it
    # fast.
    deploy: |
      set -e
      php ./drush/platformsh_generate_drush_yml.php
      # if drupal is installed, will call the following drush commands:
      #   - `cache-rebuild`
      #   - `updatedb`
      #   - and if config files are present, `config-import`
      cd public
      bash $PLATFORM_APP_DIR/drush/platformsh_deploy_drupal.sh


  relationships:
    database: 'db_drupal1:mysql'
    memcache: 'cache:memcached'

  runtime:
    extensions:
      - memcached
      - sodium
      - apcu

  disk: 512

  mounts:
    # The default Drupal files directory.
    '/public/sites/default/files':
      source: local
      source_path: 'files'
    # Drupal gets its own dedicated tmp directory. The settings.platformsh.php
    # file will automatically configure Drupal to use this directory.
    '/tmp':
      source: local
      source_path: 'tmp'
    # Private file uploads are stored outside the web root. The settings.platformsh.php
    # file will automatically configure Drupal to use this directory.
    '/private':
      source: local
      source_path: 'private'
    # Drush needs a scratch space for its own caches.
    '/.drush':
      source: local
      source_path: 'drush'
    # Drush will try to save backups to this directory, so it must be
    # writeable even though you will almost never need to use it.
    '/drush-backups':
      source: local
      source_path: 'drush-backups'

  web:
    locations:
      /drupal:
        root: 'public'
        passthru: "/drupal/index.php"
        expires: -1
        index: ["index.php"]
        allow: false
        rules:
          \.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$:
            allow: allow
          ^/robots\.txt$:
            allow: true
          ^/sitemap\.xml$:
            allow: true
          ^/drupal/sites/sites\.php$:
            scripts: false
          ^/drupal/sites/[^/]+/settings.*?\.php$:
            scripts: false
      /sites/default/files:
        allow: true
        expires: 5m
        scripts: true
        passthru: '/index.php'
        root: 'public/sites/default/files'
        rules:
          ^/drupal/sites/default/files/(css|js):
            expires: 2w
  crons:
    drupal:
      spec: '*/19 * * * *'
      cmd: 'cd public/drush ; ~/vendor/bin/drush core-cron'

server:
  build:
    flavor: none

  dependencies:
    nodejs:
      yarn: "*"
  variables:
    env:
      PUBSWEET_SECRET: superSecretThing
      NODE_ENV: production
      SERVER_PORT: 8888
      S3_BUCKET: $S3_BUCKET
      S3_PROTOCOL: https
      S3_HOST: $S3_HOST
      CLIENT_SHOW_EMAIL_LOGIN_OPTION: true
      S3_PORT: ''
      CLIENT_URL: $CLIENT_URL

  type: "nodejs:18"

  relationships:
    postgresdatabase: "dbpostgres:postgresql"
    file:
      service: minio
      endpoint: http

  disk: 512

  hooks:
  # The build hook runs after Composer to finish preparing up your code.
  # No services are available but the disk is writeable.
  build: |
    set -e
    yarn install --frozen-lockfile --production
  deploy: |
    set -e
    yarn coko-server start

  source:
    root: server

  mounts:
    "uploads":
      source: local
      source_path: uploads
    "tmp":
      source: local
      source_path: tmp
    "temp":
      source: local
      source_path: temp

    locations:
      "/graphql":
        scripts: true
        allow: true
        headers:
          Access-Control-Allow-Origin: '*'
          Access-Control-Allow-Methods: "GET, POST, OPTIONS"
          Access-Control-Allow-Credentials: "true"
          Access-Control-Allow-Headers: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
          Content-Type: "application/json; charset=utf-8;"

client:
  disk: 256
  type: "nodejs:18"

  source:
    root: client

  build:
    flavor: none

  mounts:
    "public":
      source: local
      source_path: public

  variables:
    env:
      NODE_ENV: 'production'
      CLIENT_PAGE_TITLE: 'HHMI Assessment Builder'
      CLIENT_FAVICON_PATH: '../static/favicon.ico'
      CLIENT_LANGUAGE: 'en-US'
      SERVER_URL: https://30779a260b80196a185294a3cb9a5745

  dependencies:
    nodejs:
      yarn: "*"

  hooks:
    build: |
      set -e
      yarn install --frozen-lockfile --production
      yarn coko-client-build
    post_deploy: |
      set -e
      bash $PLATFORM_APP_DIR/platformsh-scripts/hooks.deploy.sh

  # The web key configures the web server running in front of your app.
  web:
    commands:
      start: |
        sleep infinity
    locations:
      /:
        # Static site generators usually output built static files to a specific directory.
        # Define this directory (must be an actual directory inside the root directory of your app)
        # as the root for your static site.
        root: "public"
        passthru: "/index.html"
        allow: true
        # Files to consider when serving a request for a directory.
        index:
          - index.html

minio:
  type: golang:1.10

  size: L

  source:
    root: minio

  hooks:
    build: |
      set -e
      rm -rf /data/files
      rm -rf /.minio
      wget https://dl.minio.io/server/minio/release/linux-amd64/minio
      chmod +x minio
      curl https://dl.min.io/client/mc/release/linux-amd64/mc \
        --create-dirs \
        -o $HOME/minio-binaries/mc
      chmod +x $HOME/minio-binaries/mc
      export PATH=$PATH:$HOME/minio-binaries


    post_deploy: |
      set -e
      bash $PLATFORM_APP_DIR/platformsh-scripts/hooks.deploy.sh

  web:
    upstream:
      socket_family: tcp
      protocol: http

    commands:
      start: |
        ./minio server /app/minio_data --address ":$PORT" --console-address ":9000" --config-dir /app/minio_config --certs-dir /app/minio_config/certs

    locations:
      /:
        allow: false
        passthru: true

  disk: 1024
  mounts:
    '/.mc': 'shared:files/.mc'
    'minio_data':
      source: local
      source_path: minio_data_dir
    'minio_config':
      source: local
      source_path: minio_config_dir

  variables:
    env:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
